name: Package

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  package:
    name: Package distribution files
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout Source Code
        id: checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Setup Node.js 22
        id: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Package
        run: npm run package

      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Update dist" || echo "No changes to commit"
          git push origin main
