# https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
# "token.actions.githubusercontent.com:sub" =~ "repo:erhhung/ec2-github-runner:ref:refs/heads/*"
name: Testing

on:
  workflow_dispatch:

# https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
# https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps
permissions:
  contents: read # check out repository
  id-token: write # obtain JWT via OIDC
  issues: write # create approval issue

jobs:
  launch-runner:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Check out Source Code
        id: checkout
        uses: actions/checkout@v4

      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        id: aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.RUNNER_AWS_REGION }}
          role-to-assume: ${{ vars.RUNNER_OIDC_ROLE_ARN }}

      # https://github.com/erhhung/ec2-github-runner
      - name: Launch Test EC2 Runner
        id: runner
        uses: ./
        env:
          RUN_INFO: ${{ github.run_id }}-${{ github.run_attempt }}
        with:
          mode: start
          github-token: ${{ secrets.RUNNER_GITHUB_REPOS_PAT }}
          labels: Linux,ARM64,AL2023
          image-id: ${{ vars.RUNNER_ARM64_AMI_ID }}
          instance-type: ${{ vars.RUNNER_ARM64_INSTANCE_TYPE }}
          spot-instance: 'true'
          root-volume-size: '${{ vars.RUNNER_ROOT_VOLUME_SIZE }}'
          subnet-id: ${{ vars.RUNNER_SUBNET_ID }}
          security-group-id: ${{ vars.RUNNER_SECURITY_GROUP_ID }}
          iam-role-name: ${{ vars.RUNNER_INSTANCE_ROLE_NAME }}
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "github-runner-${{ env.RUN_INFO }}"},
              {"Key": "GitHubRepo", "Value": "${{ github.repository }}"}
            ]
          pre-runner-script: |
            hostname="runner-$(date '+%y%m%d%H%M')-${{ env.RUN_INFO }}" && \
            hostnamectl set-hostname $hostname  # host name == runner name
            # libicu is required by GHA Dotnet Core
            dnf update && dnf install -y git libicu

      - name: Prepare Job Output Values
        id: output
        run: |
          csv="self-hosted,${{ steps.runner.outputs.labels }}"
          cat <<EOF >> $GITHUB_OUTPUT
          labels-csv=$csv
          labels-json=["${csv//,/\",\"}"]
          EOF
    outputs:
      runner-name: ${{ steps.runner.outputs.runner-name }}
      instance-id: ${{ steps.runner.outputs.instance-id }}
      labels-json: '${{ steps.output.outputs.labels-json }}'
      labels-csv: '${{ steps.output.outputs.labels-csv }}'

  manual-approval:
    runs-on: ubuntu-latest
    needs: launch-runner
    steps:
      # https://github.com/trstringer/manual-approval
      - name: Wait for Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          issue-title: ${{ github.workflow }}
          issue-body: >-
            Please approve the termination of test runner:
            ${{ needs.launch-runner.outputs.runner-name }}
          approvers: ${{ github.triggering_actor }},${{ github.repository_owner }}
          additional-approved-words: OK
          minimum-approvals: 1

  terminate-runner:
    if: ${{ always() }}
    needs:
      - launch-runner
      - manual-approval
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Check out Source Code
        id: checkout
        uses: actions/checkout@v4

      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        id: aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.RUNNER_AWS_REGION }}
          role-to-assume: ${{ vars.RUNNER_OIDC_ROLE_ARN }}

      # https://github.com/erhhung/ec2-github-runner
      - name: Terminate Test EC2 Runner
        id: runner
        uses: ./
        with:
          mode: stop
          github-token: ${{ secrets.RUNNER_GITHUB_REPOS_PAT }}
          labels: ${{ needs.launch-runner.outputs.labels-csv }}
          instance-id: ${{ needs.launch-runner.outputs.instance-id }}
